// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JtmDvOFuD441spoBIOEKjNUabzq-Y48',
    appId: '1:1052727763580:web:8db656505cdfb6ff7c1ff9',
    messagingSenderId: '1052727763580',
    projectId: 'notes-37320',
    authDomain: 'notes-37320.firebaseapp.com',
    storageBucket: 'notes-37320.firebasestorage.app',
    measurementId: 'G-ZSJ8G839MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPD5cxhZsQz44ZZvuDcrjnrIF8ZVDSzk',
    appId: '1:1052727763580:android:5392e8e1655626fe7c1ff9',
    messagingSenderId: '1052727763580',
    projectId: 'notes-37320',
    storageBucket: 'notes-37320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyClnwndWC-9T65HXGvw59UCSIho3BZY',
    appId: '1:1052727763580:ios:508eba4c6cb989e67c1ff9',
    messagingSenderId: '1052727763580',
    projectId: 'notes-37320',
    storageBucket: 'notes-37320.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyClnwndWC-9T65HXGvw59UCSIho3BZY',
    appId: '1:1052727763580:ios:508eba4c6cb989e67c1ff9',
    messagingSenderId: '1052727763580',
    projectId: 'notes-37320',
    storageBucket: 'notes-37320.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JtmDvOFuD441spoBIOEKjNUabzq-Y48',
    appId: '1:1052727763580:web:79ca5cb33ba18ce47c1ff9',
    messagingSenderId: '1052727763580',
    projectId: 'notes-37320',
    authDomain: 'notes-37320.firebaseapp.com',
    storageBucket: 'notes-37320.firebasestorage.app',
    measurementId: 'G-MH457EYSM1',
  );
}
