// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vh_epaVSejNhnqoEJ1G7whL1NLc-WSM',
    appId: '1:676273052550:web:fc9eecbdf974da4867ea07',
    messagingSenderId: '676273052550',
    projectId: 'notes-17086',
    authDomain: 'notes-17086.firebaseapp.com',
    storageBucket: 'notes-17086.firebasestorage.app',
    measurementId: 'G-YSHJJ131LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7pEeP27Nl5LLwewD7W09io9orFCDz3g',
    appId: '1:676273052550:android:63fb7f9fd64177e367ea07',
    messagingSenderId: '676273052550',
    projectId: 'notes-17086',
    storageBucket: 'notes-17086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvXqcrIWETFeB2vc4WSCIspjLHtoIKQwU',
    appId: '1:676273052550:ios:67052520c6960eeb67ea07',
    messagingSenderId: '676273052550',
    projectId: 'notes-17086',
    storageBucket: 'notes-17086.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvXqcrIWETFeB2vc4WSCIspjLHtoIKQwU',
    appId: '1:676273052550:ios:67052520c6960eeb67ea07',
    messagingSenderId: '676273052550',
    projectId: 'notes-17086',
    storageBucket: 'notes-17086.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8vh_epaVSejNhnqoEJ1G7whL1NLc-WSM',
    appId: '1:676273052550:web:bc074c825c7ef21667ea07',
    messagingSenderId: '676273052550',
    projectId: 'notes-17086',
    authDomain: 'notes-17086.firebaseapp.com',
    storageBucket: 'notes-17086.firebasestorage.app',
    measurementId: 'G-73XG1KHMMV',
  );
}
