// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZz_lvhSpi8slzd0b1pHzLr0-0H6Y4FI',
    appId: '1:757935645236:web:ee0627a848b92cc2bae061',
    messagingSenderId: '757935645236',
    projectId: 'daftarbelanja-bdeac',
    authDomain: 'daftarbelanja-bdeac.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-bdeac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-bdeac.firebasestorage.app',
    measurementId: 'G-TJJ25YS1VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_t5Sth4uJlftJG-44iqkt3QmsUs1b8ps',
    appId: '1:757935645236:android:5c5b7457011c314dbae061',
    messagingSenderId: '757935645236',
    projectId: 'daftarbelanja-bdeac',
    databaseURL: 'https://daftarbelanja-bdeac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-bdeac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfujhzwES1dpDpmHSmmZJFcdglB6p1KAk',
    appId: '1:757935645236:ios:809fa2a8a6825af7bae061',
    messagingSenderId: '757935645236',
    projectId: 'daftarbelanja-bdeac',
    databaseURL: 'https://daftarbelanja-bdeac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-bdeac.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfujhzwES1dpDpmHSmmZJFcdglB6p1KAk',
    appId: '1:757935645236:ios:809fa2a8a6825af7bae061',
    messagingSenderId: '757935645236',
    projectId: 'daftarbelanja-bdeac',
    databaseURL: 'https://daftarbelanja-bdeac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-bdeac.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAZz_lvhSpi8slzd0b1pHzLr0-0H6Y4FI',
    appId: '1:757935645236:web:90dd5340a0d14d63bae061',
    messagingSenderId: '757935645236',
    projectId: 'daftarbelanja-bdeac',
    authDomain: 'daftarbelanja-bdeac.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-bdeac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftarbelanja-bdeac.firebasestorage.app',
    measurementId: 'G-ST27NS3JZ6',
  );
}
