// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwaYRo5ZkEnzyyhIejtfYZB_gYVepvdo',
    appId: '1:1081013229412:web:92139f190d1cc83c244c71',
    messagingSenderId: '1081013229412',
    projectId: 'mdpgold-bccf6',
    authDomain: 'mdpgold-bccf6.firebaseapp.com',
    databaseURL: 'https://mdpgold-bccf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-bccf6.firebasestorage.app',
    measurementId: 'G-XVNHPZVV6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-TLY6gnBC5pI_rqY5JYPAcEUxRnyfhk',
    appId: '1:1081013229412:android:bc86818419b8255d244c71',
    messagingSenderId: '1081013229412',
    projectId: 'mdpgold-bccf6',
    databaseURL: 'https://mdpgold-bccf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-bccf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFdDwGQ-jrXa2-bDxnOY_U_nAfXtz8XI',
    appId: '1:1081013229412:ios:1fc3c6f75a9aa562244c71',
    messagingSenderId: '1081013229412',
    projectId: 'mdpgold-bccf6',
    databaseURL: 'https://mdpgold-bccf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-bccf6.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvFdDwGQ-jrXa2-bDxnOY_U_nAfXtz8XI',
    appId: '1:1081013229412:ios:1fc3c6f75a9aa562244c71',
    messagingSenderId: '1081013229412',
    projectId: 'mdpgold-bccf6',
    databaseURL: 'https://mdpgold-bccf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-bccf6.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBwaYRo5ZkEnzyyhIejtfYZB_gYVepvdo',
    appId: '1:1081013229412:web:671cad34884c566f244c71',
    messagingSenderId: '1081013229412',
    projectId: 'mdpgold-bccf6',
    authDomain: 'mdpgold-bccf6.firebaseapp.com',
    databaseURL: 'https://mdpgold-bccf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-bccf6.firebasestorage.app',
    measurementId: 'G-JHDR2VQT7F',
  );
}
